server:
  port: 5050
  context-path: /

spring:
  application:
  name: drools
  thymeleaf:
    cache: false
    prefix: classpath:/static/pages/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5

file:
  basePath: /drool/

#Mysql数据源配置
druid:
  mysql:
    url: jdbc:mysql://10.26.12.36:3306/oyo-drools?useUnicode=true&characterEncoding=utf8
    driver-class: com.mysql.jdbc.Driver
    userName: root
    password: root
    #初始化连接大小
    initial-size: 5
    #最小空闲连接数
    min-idle: 5
    #最大连接数
    max-active: 20
    test-on-borrow: true